name: warga_plus
description: Platform Gamifikasi Edukasi Sipil & Hukum
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  provider: ^6.0.0
  google_fonts: ^6.1.0
  flutter_markdown: ^0.6.14
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  http: ^1.2.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.4
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - .env
